version: "3.9"
services:
  smart-city-staging:
    image: zephyryuusha/smart-city
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - DB_URL=${DB_URL_STAGING}  # Variáveis de ambiente criadas no github actions
      - DB_USER=${DB_USER_STAGING}
      - DB_PASSWORD=${DB_PASSWORD_STAGING}

  smart-city-production:
    image: zephyryuusha/smart-city
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=${DB_URL_PRODUCTION}  # Variáveis de ambiente criadas no github actions
      - DB_USER=${DB_USER_PRODUCTION}
      - DB_PASSWORD=${DB_PASSWORD_PRODUCTION}