services:
  smart-city-staging:
    image: zephyryuusha/smart-city  # Minha imagem no Docker Hub
    ports:
      - "8081:8080"  # Mapeia a porta 8081 do host para a porta 8080 do container
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      - SPRING_DATASOURCE_USERNAME=RM551135
      - SPRING_DATASOURCE_PASSWORD=201100

  smart-city-production:
    image: zephyryuusha/smart-city
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      - SPRING_DATASOURCE_USERNAME=RM551135
      - SPRING_DATASOURCE_PASSWORD=201100