sql
CREATE TABLE emergencies (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    accident_id NUMBER,
    status VARCHAR2(50) DEFAULT 'PENDING',
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_accident
        FOREIGN KEY (accident_id)
        REFERENCES accidents(id)
);
