CREATE TABLE accident (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    location VARCHAR2(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(50),
    PRIMARY KEY (id)
);

CREATE TABLE emergency (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    accident_id NUMBER,
    status VARCHAR2(50) DEFAULT 'PENDING',
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_accident
        FOREIGN KEY (accident_id)
        REFERENCES accident(id)
);
