name: CI/CD

on:
  push:
    branches: [ teste2-final ]  # criado para teste de workflow
  pull_request:
    branches: [ teste2-final ]  # criado para teste de workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-city .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-city

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    env:
      DB_URL: ${{ secrets.DB_URL_STAGING }}
      DB_USER: ${{ secrets.DB_USER_STAGING }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_STAGING }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml # Caminho para o arquivo docker-compose.yml
          services: smart-city-staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    env:
      DB_URL: ${{ secrets.DB_URL_PRODUCTION }}
      DB_USER: ${{ secrets.DB_USER_PRODUCTION }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_PRODUCTION }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml # Caminho para o arquivo docker-compose.yml
          services: smart-city-production