name: CI/CD

on:
  push:
    branches: [ teste2-backup ]
  pull_request:
    branches: [ teste2-backup ]

jobs:
  build:  # Job build
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test
      - name: Build with Maven
        run: mvn package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-city .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-city

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Fornece execute permission para deploy.sh
        run: chmod +x deploy.sh
      - name: Deploy to staging
        run: |
          envsubst < deploy.sh > deploy-substituted.sh
          chmod +x deploy-substituted.sh
          docker-compose run smart-city-staging ./deploy-substituted.sh staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          envsubst < deploy.sh > deploy-substituted.sh
          chmod +x deploy-substituted.sh
          docker-compose run smart-city-staging ./deploy-substituted.sh production