name: CI/CD

on:
  push:
    branches: [ teste2-backup ]
  pull_request:
    branches: [ teste2-backup ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test
      - name: Build with Maven
        run: mvn package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-city .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-city

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Instalar o Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Deploy to staging
        run: |
          docker-compose run --entrypoint "" smart-city-staging sh -c "envsubst < /app/deploy.sh > /app/deploy-substituted.sh"
          docker-compose run smart-city-staging sh -c "chmod +x /app/deploy-substituted.sh 
           && /app/deploy-substituted.sh staging" 

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to production
        run: |
          docker-compose run --entrypoint "" smart-city-production sh -c "envsubst < /app/deploy.sh > /app/deploy-substituted.sh"          docker-compose run smart-city-production sh -c "chmod +x /app/deploy-substituted.sh 
          && /app/deploy-substituted.sh production"